### ISSUE TITLE
It does not appear possible to post facts to the classification object

### ISSUE THREAD

**Issue by mhjacks** [puppetlabs/puppet-classify#10]
As a user, I would like to be able to post facts to the classification API to test classification rules.  The current implementation provides no mechanism to pass the facts and trusted hashes into the classification method.

**Comment by briancain** [comment]
@mhjacks - Ah yes, it looks like the ability to POST facts to the classification endpoint was added. Thanks for creating the issue! When the feature is added, I'll ping you on this issue.

**Comment by mhjacks** [comment]
Great, thanks!  binford2k said he might submit a PR for this and asked me to open an issue to track it.

**Comment by briancain** [comment]
Ah excellent. @binford2k let me know if you plan on doing this and I'd be happy to test the PR and merge.

**Comment by briancain** [comment]
@mhjacks this looked to be auto-closed when I merged the PR. I cut a new release of the gem, and this fix should be in 0.1.3. Let me know if that works for you, thanks!
