### ISSUE TITLE
tags to match gem releases

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/puppet-classify#15]
It'd be nice :)

**Comment by briancain** [comment]
Hey @brettswift , do you mean git tags?

**Comment by briancain** [comment]
@brettswift - pushed a tag for version `0.1.5` which is the latest release https://github.com/puppetlabs/puppet-classify/tree/0.1.5

**Comment by briancain** [comment]
@brettswift - annndd pushed several more tags. Hope that helps! If you need any more tags let me know, I just went back to around `0.1.2`. If not I can close the issue.

**Comment by brettswift** [comment]
Thanks!

Was just curious to see changes between versions more clearly.

And it's also good for contributors.

Love this module btw. We have on demand capability for "feature branch"
testing of our control repo and build ephemeral puppetmasters to test. This
gem is used in a bootstrap script after PE is installed to make the feature
branch the default branch in the environment classification.

It was a big help!

We also use it for batching environment node groups.

**Comment by briancain** [comment]
@brettswift - Certainly! Hopefully now with tags it's a bit clearer what changes are made between versions.

I'm so happy to hear that it's been useful to you all!
