### ISSUE TITLE
resolve group classification rule

### ISSUE THREAD

**Issue by bilsch** [puppetlabs/puppet-classify#2]
not sure if there is another way to reach out - this is not an issue but more a question on use of the api.

I'm trying to find out how to access the result of a fact based rule for group membership. I ultimately want to get a list of hosts matching a rule.

I get all of the information I want/need if the node has been pinned but for some reason the rule and wild card matching - I can't find any object containing the node names. I had thought classification.explain(node) would provide this detail but it does not appear to do so. By chance is there something behind the scenes which could be added to show the same information as is on the tab "Matching nodes" as a key on the groups.get_group hash?

For my use-case it would also be helpful if I could get the classes a named host ultimately gets ( again why I was poking at classification.explain )

**Comment by briancain** [comment]
Hey @bilsch, I'm not entirely sure how to do this. But since this is a node classifier API question, I would recommend you ask it on the [pe-users](https://groups.google.com/a/puppetlabs.com/forum/#!forum/pe-users) email list. Someone on there should be able to help you!

**Comment by bilsch** [comment]
@briancain ack thanks!
