### ISSUE TITLE
environment_trumps  causes a failure

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/puppet-classify#3]
When the `environment_trumps` parameter is included on the groups api,  for a new group without an ID,  a 400 response code is given.  

I've also seen this with the update group api.

**Comment by briancain** [comment]
Hey @brettswift , do you have an example json hash that you used to generate the 400 response code? An HTTP 400 from the classifier usually means it was a bad request i.e. something wrong with the json sent to the API.

**Comment by brettswift** [comment]
This is what I am trying to send: 

``` ruby
environment = 'an_environment_test'

$new_env = {
   "parent"             => "#{prod_env_id}",
   "name"               => "#{environment}",
   "environment"        => "#{environment}",
   "environment_trumps" => "true",
   "description"        => "created at bootstrap time",
   "classes"            => {},
   "rule"               => [
      "and",
      [
         "~",
         [
            "fact",
            "clientcert"
         ],
         ".*"
      ]
   ]
}

puppetclassify.groups.create_group($new_env)
```

which results in 

``` shell
An error occured creating the group: HTTP 400 Bad Request
```

If I comment out the environment_trumps line,  it works: 

``` ruby
environment = 'an_environment_test'

$new_env = {
   "parent"             => "#{prod_env_id}",
   "name"               => "#{environment}",
   "environment"        => "#{environment}",
#   "environment_trumps" => "true",
   "description"        => "created at bootstrap time",
   "classes"            => {},
   "rule"               => [
      "and",
      [
         "~",
         [
            "fact",
            "clientcert"
         ],
         ".*"
      ]
   ]
}
puppetclassify.groups.create_group($new_env)
```

Group is created, but obviously not set to an environment group.   Maybe this is a bug in the classifier API and not this gem?   I tried putting more debug messages in groups.rb but when I run it puppet seems to recognize that and replace the file..   so I'm not sure how to help out more on my end.

**Comment by brettswift** [comment]
hmm... strange,  well there has been a long weekend between when I tried this last, and I surely remember trying this last week and it wasn't working.    

However, I just had it work - with the environment_trumps taking true as a boolean and not a string.. ie: get rid of the quotes.. and it works.

**Comment by briancain** [comment]
@brettswift ah yep! That is what I was going to mention....the flags that take an boolean value are just the literal `true` or `false` and aren't wrapped in a string. Glad it works now!
